Update node-providers.md
ethereum-optimism/developers pull request #19
Opened 2023-10-26 15:29 UTC by konstantinrm

**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

2023-10-26 15:39 UTC, sbvegan requested changes
Just a few updates and then I can merge this in. Thanks for your contribution!

2023-10-30 10:50 UTC, konstantinrm commented on community/node-providers.md
> +### Description and Pricing
Done

2023-10-30 10:50 UTC, konstantinrm commented on community/node-providers.md
> +## DRPC.ORG
Done

2023-10-30 10:50 UTC, konstantinrm commented on community/node-providers.md
> +[DRPC](https://drpc.org/) provides auto-scalable Optimism RPC (Full & Archive) nodes and RPCs for 24+ other chains. DRPC supports Websocket and all methods, including debug and trace methods. For ear
Fixed

2023-10-30 14:19 UTC, sbvegan approved these changes
Thanks for making those updates and contributing to our repo!

2023-10-30 14:19 UTC, merged